import '../styles.css';

type VibeKey = 'street' | 'dreamy' | 'chill' | 'playful' | 'romantic' | 'dramatic';
type Cue = { label: string; score: number };
const $ = <T extends HTMLElement>(id: string) => document.getElementById(id) as T;
const video = $('camera') as HTMLVideoElement;
const image = $('uploadedImage') as HTMLImageElement;
const canvas = $('captureCanvas') as HTMLCanvasElement;

const songs: Record<VibeKey, [string, string, string, string][]> = {
  street: [['Kuthanthram', 'Dabzee', '🎙', 'street'], ['Illuminati', 'Dabzee', '⚡', 'street'], ['Hukum', 'Anirudh Ravichander', '🔥', 'street'], ['Nonstop', 'Drake', '🛼', 'street']],
  dreamy: [['Malare', 'Vijay Yesudas', '☁', 'dreamy'], ['Pavizha Mazha', 'KS Harisankar', '🌥', 'dreamy'], ['Golden Hour', 'JVKE', '⛅', 'dreamy'], ['Space Song', 'Beach House', '🌙', 'dreamy']],
  chill: [['Darshana', 'Hesham Abdul Wahab', '🌊', 'chill'], ['Onakka Munthiri', 'Divya Vineeth', '🍃', 'chill'], ['Sunset Lover', 'Petit Biscuit', '☀', 'chill'], ['Mundane', 'Pritam', '🫧', 'chill']],
  playful: [['Manavalan Thug', 'Dabzee', '🕺', 'playful'], ['Kudukku', 'Vineeth Sreenivasan', '🍬', 'playful'], ['What Makes You Beautiful', 'One Direction', '🎈', 'playful'], ['Jalabulajangu', 'Anirudh', '🎉', 'playful']],
  romantic: [['Aaradhike', 'Vineeth Sreenivasan', '🌷', 'romantic'], ['Nee Himamazhayayi', 'KS Harisankar', '💌', 'romantic'], ['Until I Found You', 'Stephen Sanchez', '🩷', 'romantic'], ['Aankhon Se Batana', 'Dikshant', '🌸', 'romantic']],
  dramatic: [['Kalapakkaara', 'Shreya Ghoshal', '👑', 'dramatic'], ['Jeevamshamayi', 'KS Harisankar', '🌘', 'dramatic'], ['Believer', 'Imagine Dragons', '🌩', 'dramatic'], ['Thee Thalapathy', 'Silambarasan', '⚔', 'dramatic']],
};
const vibes: Record<VibeKey, { name: string; desc: string; orb: string }> = {
  street: { name: 'Street / Main Character', desc: 'Bold fit. Big energy. You walked in, scene changed.', orb: '⚡' },
  dreamy: { name: 'Dreamy', desc: 'Soft colours and calm energy. A little moonlight moment.', orb: '☁' },
  chill: { name: 'Chill', desc: 'Easy look, easy mood. This one needs window-seat music.', orb: '☼' },
  playful: { name: 'Full On Fun', desc: 'Colour, chaos and good vibes. Nalla scene aanu.', orb: '✦' },
  romantic: { name: 'Soft Launch', desc: 'Looking like a love-song montage, respectfully.', orb: '♥' },
  dramatic: { name: 'Cinematic', desc: 'A little mysterious. A lot of entrance music.', orb: '✧' },
};
let stream: MediaStream | undefined; let facing: 'user' | 'environment' = 'user'; let activeVibe: VibeKey | null = null; let locked = false; let scanId = 0; let workerReady = false;
const worker = new Worker(new URL('./vision-worker.ts', import.meta.url), { type: 'module' });
function showToast(message: string) { const toast = $('toast'); toast.textContent = message; toast.classList.add('show'); window.setTimeout(() => toast.classList.remove('show'), 2600); }
function setStatus(text: string) { $('scanTitle').textContent = text; $('scanToast').hidden = false; }
function hideStatus() { $('scanToast').hidden = true; }
function search(song: readonly [string, string, string, string]) { return `https://www.youtube.com/results?search_query=${encodeURIComponent(`${song[0]} ${song[1]}`)}`; }
function render(vibe: VibeKey, cues: string[]) { const info = vibes[vibe]; activeVibe = vibe; $('vibeName').textContent = info.name; $('vibeDescription').textContent = info.desc; $('vibeOrb').textContent = info.orb; $('vibeOrb').className = `vibe-orb ${vibe}`; $('cueChips').innerHTML = cues.map((cue) => `<span>${cue}</span>`).join('') || '<span>visual vibe detected</span>'; $('songIntro').textContent = `${info.name} energy, delivered with pattu.`; $('songList').innerHTML = songs[vibe].map((song, index) => `<article class="song"><div class="cover ${song[3]}">${song[2]}</div><div class="song-info"><strong>${song[0]}</strong><small>${song[1]} · ${index === 0 ? 'perfect match' : 'vibe match'}</small></div><a class="listen" target="_blank" rel="noopener" href="${search(song)}">Listen ↗</a></article>`).join(''); }
function scoreVibe(cues: Cue[]): { vibe: VibeKey; labels: string[] } { const scores: Record<VibeKey, number> = { street: 0, dreamy: 0, chill: 0, playful: 0, romantic: 0, dramatic: 0 }; const labels = cues.slice(0, 4).map((cue) => cue.label.replace('a person ', '').replace('wearing ', '')); for (const cue of cues) { const s = cue.score; if (cue.label.includes('dark streetwear') || cue.label.includes('sunglasses') || cue.label.includes('jewellery')) scores.street += s; if (cue.label.includes('pastel') || cue.label.includes('calm expression')) scores.dreamy += s; if (cue.label.includes('relaxed')) scores.chill += s; if (cue.label.includes('bright') || cue.label.includes('patterned')) scores.playful += s; if (cue.label.includes('elegant') || cue.label.includes('happy smile')) scores.romantic += s; if (cue.label.includes('black dramatic')) scores.dramatic += s; } const vibe = (Object.entries(scores).sort((a, b) => b[1] - a[1])[0][0] as VibeKey); return { vibe: scores[vibe] > 0 ? vibe : 'chill', labels }; }
async function startCamera() { try { stopCamera(); stream = await navigator.mediaDevices.getUserMedia({ video: { facingMode: facing, width: { ideal: 1080 }, height: { ideal: 1440 } }, audio: false }); video.srcObject = stream; await video.play(); $('cameraEmpty').hidden = true; $('cameraHud').hidden = false; $('cameraStatus').innerHTML = '<i></i> Live'; ($('stopCamera') as HTMLButtonElement).disabled = false; image.hidden = true; } catch { showToast('Camera access is needed — or use a photo instead.'); } }
function stopCamera() { stream?.getTracks().forEach((track) => track.stop()); stream = undefined; video.srcObject = null; $('cameraHud').hidden = true; $('cameraStatus').innerHTML = '<i></i> Ready'; ($('stopCamera') as HTMLButtonElement).disabled = true; }
function snapshot(): ImageBitmap | null { const source = image.hidden ? video : image; if (source === video && (!stream || video.readyState < HTMLMediaElement.HAVE_CURRENT_DATA)) return null; canvas.width = source === video ? video.videoWidth : image.naturalWidth; canvas.height = source === video ? video.videoHeight : image.naturalHeight; const context = canvas.getContext('2d'); if (!context || !canvas.width || !canvas.height) return null; context.drawImage(source, 0, 0, canvas.width, canvas.height); return null; }
async function scan() { if (locked) return showToast('Vibe is locked. Unlock it to scan again.'); if (!workerReady) { setStatus('Downloading your private vibe brain...'); worker.postMessage({ type: 'load' }); return; } const source = image.hidden ? video : image; if (source === video && (!stream || video.readyState < HTMLMediaElement.HAVE_CURRENT_DATA)) return showToast('Start the camera first.'); setStatus('Reading the drip...'); $('scanText').textContent = 'Checking outfit, accessories, expression and objects'; const context = canvas.getContext('2d'); canvas.width = source === video ? video.videoWidth : image.naturalWidth; canvas.height = source === video ? video.videoHeight : image.naturalHeight; if (!context || !canvas.width || !canvas.height) return showToast('That image is not ready yet.'); context.drawImage(source, 0, 0, canvas.width, canvas.height); worker.postMessage({ type: 'classify', id: ++scanId, image: canvas.toDataURL('image/jpeg', 0.82) }); }
worker.onmessage = ({ data }) => { if (data.type === 'progress') { setStatus(data.progress ? `Downloading model: ${Math.round(data.progress)}%` : 'Preparing the vibe model...'); return; } if (data.type === 'ready') { workerReady = true; hideStatus(); showToast('Vibe brain ready. Scan your look ✦'); return; } if (data.type === 'result') { if (data.id !== scanId) return; hideStatus(); const result = scoreVibe(data.cues as Cue[]); render(result.vibe, result.labels); showToast(`Ithinoru pattu kitti — ${vibes[result.vibe].name}!`); return; } if (data.type === 'error') { hideStatus(); showToast('Model could not load. Check your connection and try again.'); } };
$('startCamera').onclick = startCamera; $('stopCamera').onclick = () => { stopCamera(); $('cameraEmpty').hidden = false; }; $('scanButton').onclick = scan; $('flipCamera').onclick = () => { facing = facing === 'user' ? 'environment' : 'user'; startCamera(); }; $('imageInput').onchange = (event) => { const file = (event.target as HTMLInputElement).files?.[0]; if (!file) return; stopCamera(); image.onload = () => { image.hidden = false; $('cameraEmpty').hidden = true; scan(); }; image.src = URL.createObjectURL(file); }; $('lockVibe').onclick = () => { locked = !locked; showToast(locked ? 'Vibe locked. Your pattu stays.' : 'Vibe unlocked.'); }; $('anotherSong').onclick = () => { if (!activeVibe) return showToast('Scan a look first.'); songs[activeVibe].push(songs[activeVibe].shift()!); render(activeVibe, []); }; document.querySelectorAll<HTMLElement>('[data-page]').forEach((button) => { button.onclick = () => { document.querySelectorAll<HTMLElement>('[data-page]').forEach((item) => item.classList.toggle('active', item.dataset.page === button.dataset.page)); if (button.dataset.page === 'gallery') $('imageInput').click(); if (button.dataset.page === 'saved') showToast('Saved songs are coming in the next beat.'); if (button.dataset.page === 'settings') showToast('Settings are coming soon.'); }; });
